---
- name: Install wordpress
  get_url:
    url: http://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz
    dest: /var/www/html

- name: Unarchive wordpress
  unarchive:
    src: /var/www/html/wordpress-{{ wordpress_version }}.tar.gz
    dest: /var/www/html

- name: Copy the wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
